---
  - hosts: odoo
    remote_user: cahbecker
    become: yes
    tasks:
      - name: "Executa o container MySQL"
        docker_container:
          name: db
          image: postgres:9.4
          env:
            POSTGRES_PASSWORD: odoo
      - name: "Executa o container WordPress"
        docker_container:
          name: odoo
          image: odoo
          links:
            - "db:db"
          ports:
            - "8069:8069"